language: node_js
node_js:
  - "lts/*"
before_script:
  - chmod a+x ./deploy.sh
script:
  - npm run build
cache: npm
# cache:
#   directories:
#     - node_modules
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      all_branches: true